version: '3'
services:
  app:
    container_name: app
    build: ./
    ports:
      - "8888:8000"
    restart: always
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./database_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass
